function MakeJsDownloadProof($filename) {
    $file = [System.IO.File]::ReadAllText("$PSScriptRoot\$filename")
    $file = $file.Replace("\", "\\").Replace("'", "\'").Replace("`n", "\r\n")
    return $file
}

function MakeUriProof($filename) {
    $file = [System.IO.File]::ReadAllLines("$PSScriptRoot\$filename")
    $result = '';
    foreach($line in $file) {
        $result += $line.Trim().Replace('"', "&quot;")
    }
    return $result
}

function ReplaceWithFile($template, $token, $filename, $isUri) {
    if($isUri -eq $true) {
        $file = MakeUriProof $filename
    } else {
        $file = MakeJsDownloadProof $filename
    }
    $template = $template.Replace("{{$token}}", $file)
    return $template
}

$template = Get-Content "$PSScriptRoot\page.html"

# Replace first line with auto-generated warning
$template[0] = "<!-- This file is automatically generated using https://github.com/jorik90/lastpass-rdp-starter/blob/master/src/build.ps1 -->"

# Include startmstsc.cmd
$template = ReplaceWithFile $template "mstsc.cmd" "startmstsc.cmd" $false

# Include rdp-uri.reg
$template = ReplaceWithFile $template "rdp-uri.reg" "rdp-uri.reg" $false

# Include bookmarklet.js
$template = ReplaceWithFile $template "bookmarklet.js" "bookmarklet.js" $true


$template | Out-File "$PSScriptRoot\lastpass-rdp-starter.html"